---
title: "About"
---
### Data Science (R, Python, SQL)
#### Master of Environmental Data Science (MEDS) (Pending June 2025), Bren School of Environmental Science & Management – University of California, Santa Barbara (UCSB)
- Capstone Project: Industrial Energy Data Exploration Interface (analyzing energy use and efficiency metrics)
- Highlighted Coursework: Statistics for Environmental Data Science, Geospatial Analysis, Ethics and Bias in Environmental Data Science, Machine Learning, Data Visualization and Communication, Environmental Policy Evaluation, Data Management, Modeling Environmental Systems (all to be completed by 6/25)
- Leadership: MEDS Class Co-Chair 
- Employment: Career Development Student Assistant

### Ecology and Drones
#### LSA Associates Inc., Carlsbad, CA. Assistant Biologist, Drone Pilot (8/21 – 7/24)
- Operated drone flights to collect and process aerial imagery into a 3D orthomosaic. Data is then transferred to ESRI ArcGIS platforms for further analysis. 
- Participate in a wide variety of wildlife surveys across a range of ecosystems for plant and animal species inventory, special-status species and habitat in the southern California region.
- Biological report writing for a variety of cities, counties, and jurisdictions across Southern California. 
- Performed jurisdictional delineations for assigning CDFW, Regional Water Quality Control Board, US Army Corps of Engineers jurisdiction of wetland and non-wetland waters.

#### San Diego Zoo Wildlife Alliance, Escondido and San Diego, CA. Wildlife Care Associate, Hoofstock Rotation (10/20 – 4/21)
- Operated heavy machinery, maintaining area cleanliness, behavioral observation, and assisting with other projects.

#### Rhino Reproduction Research Assistant (10/19 – 10/20)
- Managed data cataloging and analysis for Rhinoceros reproduction research studies.

#### Animal Care Center Summer Intern (6/19 – 9/19)
- Provided animal neonate care such as milk-ratio data cataloging, behavioral observation, and reintroduction.

### Energy

My capstone project, the Industrial Energy Data Exploration Interface, a project for the [Master of Environmental Data Science](https://bren.ucsb.edu/masters-programs/master-environmental-data-science) at [Bren School of Environmental Science and Management](https://bren.ucsb.edu/), University of California, Santa Barbara.

A full [project summary is available on the Bren Website](https://bren.ucsb.edu/projects/industrial-energy-data-exploration-interface).

In short, the overarching goal of this project is to create an industrial energy efficiency data interface, built upon the IAC dataset, that will enable ISAL researchers to streamline and advance their research into industrial decarbonization pathways. To achieve this goal, the project team will focus on the following two key objectives. 
1. Design a flexible and scalable data structure that simplifies the integration of new data and facilitates complex queries with multiple inputs.
2. Develop an interactive data visualization tool that helps researchers visualize trends, uncover insights, and propose solutions for decarbonizing the industrial sector through improved energy efficiency.

Here is the [Industrial Energy Github Repository](https://github.com/IndustrialEnergy) associated with this project. 



